# config/_default/languages.en.toml

languageCode = "en-us"
languageName = "English"
weight = 1

[params]
  displayName = "study_blog"
  description = "My journey into pwn/re and CTFs"

  [params.homepage]
    layout = "profile"
    showRecent = true

  [params.author]
    name = "sigchill"
    image = "my_avatar.jpeg"
    headline = "pwn/re Enthusiast & CTF Player"
    bio = "Welcome to my study blog. Here I document my CTF writeups and security research."
    
  [[social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/sigchill"
  weight = 1

[[social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/_sigchill"
  weight = 2