languageCode = "en"
languageName = "English"
weight = 1
title = "Study Blog"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "sigchill"
  email = "yabinbobbi@gmail.com"
  image = "assets/my_avatar.jpeg"
  headline = "My study blog"
  bio = "i do application security research at least i think so."
  links = [
    { x-twitter = "https://twitter.com/_sigchill" },
    { github = "https://github.com/sigchill" },
  ]