# config/_default/languages.en.toml

languageCode = "en-us"
languageName = "English"
weight = 1

[params]
  displayName = "study_blog"
  description = "My journey into AppSec and CTFs"

  [params.homepage]
    layout = "profile"
    showRecent = true

  [params.author]
    name = "sigchill"
    image = "my_avatar.jpeg" # Ensure this file is inside your 'assets/' folder!
    headline = "AppSec Engineer & CTF Player"
    bio = "Welcome to my study blog. Here I document my CTF writeups and security research."

    [[params.author.links]]
      name = "GitHub"
      icon = "github"
      url = "https://github.com/sigchill"

    [[params.author.links]]
      name = "Twitter"
      icon = "twitter"
      url = "https://twitter.com/_sigchill"