baseURL = 'https://sigchill.github.io/study_blog/'
languageCode = 'en-us'
title = 'study_blog'
theme = 'hugo-theme-terminal'
[caches]
  [caches.images]
    dir = ':cacheDir/images'


[menu]
[[menu.main]]
	name = 'whoami'
	pageRef = '/aboutme/'
	weight = 1

[[menu.main]]
	name = 'CTFs'
	pageRef = '/ctfs/'
	weight = 2


[[menu.main]]
	name = 'Blog'
	pageRef = '/posts/'
	weight = 3



[[menu.main]]
	name = 'Programming'
	pageRef = '/programming'
	weight = 4
